import tailwindcss from '@tailwindcss/vite';
import { sveltekit } from '@sveltejs/kit/vite';
import { existsSync, readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'vite';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, '..');

/**
 * Resolves a JSON data file with a list of fallback locations.
 * Used by the `cards-data-fallback` plugin below so the SvelteKit build
 * doesn't fail when `static/content/*.json` haven't been synced yet — the
 * backend folder is the source of truth, so cards.json is always available
 * (it's tracked in git) while card-relations.json can also be generated by
 * `npm run content:relations` and synced into `static/content/`.
 */
function readJsonWithFallback(candidates: string[]): string {
  for (const candidate of candidates) {
    try {
      const fullPath = resolve(projectRoot, candidate);
      if (existsSync(fullPath)) {
        return readFileSync(fullPath, 'utf-8');
      }
    } catch {
      // try next candidate
    }
  }
  return '{}';
}

/**
 * Virtual modules for the cards dataset and the relations map.
 * `content.ts` imports from these; the resolver below tries multiple paths
 * at build time, so a fresh clone (no `static/content/*.json` synced yet)
 * can still build as long as the backend has the source files.
 */
const cardsDataFallbackPlugin = {
  name: 'cards-data-fallback',
  resolveId(id: string) {
    if (id === 'virtual:cards-data' || id === 'virtual:relations-data') {
      return '\0' + id;
    }
  },
  load(id: string) {
    if (id === '\0virtual:cards-data') {
      const content = readJsonWithFallback([
        'backend/cards.json',
        'frontend/static/content/cards.json',
      ]);
      return `export default ${content};`;
    }
    if (id === '\0virtual:relations-data') {
      const content = readJsonWithFallback([
        'frontend/static/content/card-relations.json',
        'backend/card-relations.json',
      ]);
      return `export default ${content};`;
    }
  },
};

export default defineConfig({ plugins: [tailwindcss(), sveltekit(), cardsDataFallbackPlugin] });
